### ISSUE TITLE
live examples on gh-pages

### ISSUE THREAD

**Issue by noerw** [nickpeihl/leaflet-sidebar-v2#14]
would be nice to host the examples on gh-pages (configured to `master` branch, root dir), and link to them in readme and repo URL

**Comment by nickpeihl** [comment]
Good idea. I'm on vacation this week so this may have to wait until I get back.

**Comment by nickpeihl** [comment]
Hi @noerw, I've turned on gh-pages for this repo. Since I also host my personal website from GitHub, the pages automatically redirect from nickpeihl.github.io to npeihl.com. So they can be accessed from http://npeihl.com/leaflet-sidebar-v2/examples. I've added the above link in the GitHub header and links to the examples in the README.

Fixed in 09086d779e4fd04e3a65aa8031e340e8a3691bbe.
