### ISSUE TITLE
Close and open the sidebar simultaneously

### ISSUE THREAD

**Issue by matheussiba** [nickpeihl/leaflet-sidebar-v2#21]
I was using the leaflet-sidebar-v2 API and because a chain of processes my code was closing the sidebar and opening it in a new tab, while the  `autopan: true` . The center of my map was always getting displaced, all the time the sidebar was being opened again. 

It's not the case, but just to understand the bug: 
Imagine you have this following button, that all the time you click on it, it closes the sidebar and open a tab. Remembering `autopan: true` . If you click on it twice. The center of the map will be displaced. 
 ```
<button id="btn_test">TEST</button>

    $( "#btn_test" ).click(function() {
      ctlSidebar.close(); 
      ctlSidebar.open("home");
    });
```

It's not a big deal, but it took me so long to realize why it was being caused. And I decided to post it here maybe others face the same or it possibly get corrected in future releases.

**Comment by noerw** [comment]
Hey @matheussiba,
thanks for the heads up.

This also happens if you just open & close the sidebar very quickly by quickly clicking the panel button twice.
I'll see if we can avoid this behaviour, but I presume it's an issue with leaflets pan animation.

In your code, you could just remove the call to `ctlSidebar.close()` and directly open the new panel.
