### ISSUE TITLE
Sidebar is created outside map div

### ISSUE THREAD

**Issue by christophfriedrich** [nickpeihl/leaflet-sidebar-v2#8]
I think it's not intuitive to append the sidebar div to `document.body` instead of the map div. I want the sidebar to be displayed within the map even if that map doesn't span the entire viewport.

I fixed this for me by changing [line 33 in the js](https://github.com/nickpeihl/leaflet-sidebar-v2/blob/master/js/leaflet-sidebar.js#L33) from
```
 this._sidebar = L.DomUtil.create('div', 'sidebar collapsed', document.body);
```
to
```
 this._sidebar = L.DomUtil.create('div', 'sidebar collapsed', L.DomUtil.get('map'));
```
Would you too consider that a smarter default or am I missing a point?
Anyways, thanks for your work!

**Comment by nickpeihl** [comment]
Thanks for your suggestion. I'm not opposed to the idea of adding the sidebar to the map container instead of the `body`. But I wasn't able to get your method to work in a [quick trial](https://glitch.com/edit/#!/wood-windshield?path=index.html:15:23).  Additionally, I think your method would also require us to pass in the `id` of the map div which might not always be `'map'`. 

I think the best way forward is to refactor the code to be similar to how [other Leaflet controls](https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Layers.js#L176) are add to the map. I'd be happy to review a pull request if you are willing to.

**Comment by christophfriedrich** [comment]
I made a [minimal version where my method works](https://glitch.com/edit/#!/plain-single?path=sidebar-edited.js:36:10).

I don't really understand how it's done in your link - where is the container added to any element?!

You're right that the map div `id` could be something other than `'map'`. I'd suggest: Leave line 33 as it is (so that the sidebar is created outside at first) and modify the `addTo` method so that it moves the sidebar HTML element inside the map specified there (that would be intuitive imo).

A problem that arises then: Click events on the map are also emitted when the user clicks on the sidebar, which I think is not desirable.

**Comment by nickpeihl** [comment]
Yes, I agree. Modifying the `addTo` method is probably the best option. Perhaps the [other Leaflet controls](https://github.com/Leaflet/Leaflet/tree/master/src/control) might give a clue on how to avoid map click events?

**Comment by noerw** [comment]
The reason for the current implementation is to support the static definition of panes in HTML while allowing modification through the sidebar API.

Leaflet controls store their container within the map div, [but the DOM insertion is handled by Leaflet's plugin API itself](https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.js#L64-L83).
In general the inner content of the leaflet map div should not be manually touched.

This leaves the option to move the childNodes of a static `div.sidebar` into the container that will be passed to Leaflet.
I will try this and see if it works
